# parameters:
  # service_name: service name
  # service_manager: service/supervisor/systemd

- name: stop service by service command
  tags:
    - service
  service:
    name: "{{ service_name}}"
    state: stopped
  when: service_manager is defined and service_manager == 'service'

- name: stop service by supervisorctl command
  tags:
    - service
  supervisorctl:
    name: "{{ service_name}}"
    state: stopped
  when: service_manager is defined and service_manager == 'supervisor'

- name: stop service by systemctl command
  tags:
    - service
  systemd:
    name: "{{ service_name}}"
    state: stopped
  when: service_manager is defined and service_manager == 'systemd'

