
environment:
  APP_NAME: sample

# pipeline模板
pipeline:
- name: build
  environment:
    HELLO: world
  tasks:
    - task.id: sample
      arg1: world-${env.HELLO}
  after-tasks:
    - task.id: sample
      arg1: world-${env.HELLO}
