
environment:
  APP_NAME: sample

# pipeline模板
pipeline:
- name: build
  environment:
    WORLD: world
  tasks:
    - task.id: sample
      arg1: hello-${env.WORLD}
    - task.id: script
      code: |
        echo "echo $WORLD"
    - task.id: script
      code: ./jenkins.sh build
  after-tasks:
    - script:
        code: ./jenkins.sh test
