
environment:
  APP_NAME: sample

# pipeline模板
pipeline:
- name: build
  environment:
    WORLD: world
  tasks:
    - task.id: sample
      arg1: hello-${env.WORLD}
    - script:
        code: ./jenkins.sh
    - task.id: script
      code: |
        echo "hello, world"
        echo "hello, world"
        echo "hello, world"
        echo "hello, world"
        echo "hello, world"
        echo "hello, world"
        echo "hello, world"
        echo "hello, world"
        echo "hello, ${WORLD}"
