
environment:
  APP_NAME: sample

# pipeline模板
pipeline:
- name: build
  environment:
    WORLD: world
  tasks:
    - task.id: asl-tasks/sample
      arg1: hello-${env.WORLD}
    - task.id: script
      code: |
        echo "echo $WORLD"
    - task.id: script
      code: ./jenkins.sh build
  when:
    environment:
      WORLD: world
