# parameters:
  # service_name: service name
  # service_manager: service/supervisor/systemd

- name: reload service by service command
  tags:
    - service
  service:
    name: "{{ service_name}}"
    state: reloaded
  when: service_manager is defined and service_manager == 'service'

- name: reload service by systemctl command
  tags:
    - service
  systemd:
    name: "{{ service_name}}"
    state: reloaded
  when: service_manager is defined and service_manager == 'systemd'

