# parameters:
  # service_name: service name
  # service_manager: service/supervisor/systemd

- name: stop service by service command
  tags:
    - service
  service:
    name: "{{ service_name}}"
    state: stopped
  when: service_manager is defined and service_manager == 'service'

- name: stop service by supervisorctl command
  tags:
    - service
  supervisorctl:
    name: "{{ service_name}}"
    state: stopped
  when: service_manager is defined and service_manager == 'supervisor'

- name: stop service by systemctl command
  tags:
    - service
  systemd:
    name: "{{ service_name}}"
    state: stopped
  when: service_manager is defined and service_manager == 'systemd'

- name: stop service by storm command
  tags:
    - service
  block:
    - name: list storm app
      shell: "{{ storm_home }}/bin/storm list |grep {{ service_name }}"
      register: _reg_storm_list
      ignore_errors: true
    - name: kill storm app
      shell: "{{ storm_home }}/bin/storm kill {{ service_name }} -w 30"
      when: _reg_storm_list.rc == 0
    - name: sleep
      shell: sleep 10
  when: service_manager is defined and service_manager == 'storm'

