# parameters:
  # service_name: service name
  # service_manager: service/supervisor/systemd
  #
- name: start service by service command
  tags:
    - service
  service:
    name: "{{ service_name }}"
    state: started
  when: service_manager is defined and service_manager == 'service'

- name: start service by supervisorctl command
  tags:
    - service
  supervisorctl:
    name: "{{ service_name }}"
    state: started
  when: service_manager is defined and service_manager == 'supervisor'

- name: start service by systemctl command
  tags:
    - service
  systemd:
    name: "{{ service_name}}"
    state: started
  when: service_manager is defined and service_manager == 'systemd'

- name: start service by storm command
  tags:
    - service
  block:
    - name: sleep 10 seconds
      pause:
        seconds: 10
    - name: start storm app
      shell: "{{ storm_home }}/bin/storm jar {{ _app_install_dir }}/{{ app_name }}.jar {{ storm_topology_class }}"
  when: service_manager is defined and service_manager == 'storm'


